---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "/home/pi/vault-test/"
    state: directory
    mode: '0755'

- name: Copy template to target
  ansible.builtin.template:
    src: templates/application.yml.j2
    dest: "/home/pi/vault-test/application.yml"
  no_log: false
